apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomato-health-api
  labels:
    app: tomato-health-api
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomato-health-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 # zero-downtime deploys
  template:
    metadata:
      labels:
        app: tomato-health-api
    spec:
      containers:
        - name: api
          image: anangwe/tomato-health-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1500m"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
